package com.compass.msclaudit.feignclients.response;

public enum Status {

	PAYMENT_SUCCESSFUL,
	PAYMENT_NOT_FOUND,
	PAYMENT_INACTIVE,
	PAYMENT_NOT_INSTALLMENT,
	PAYMENT_AMOUNT_NOT_AVAIABLE,
	PROCESSING_PAYMENT;
	
}
